@module={{host}}/general
@token = {{login.response.body.message}}
@today={{$localDatetime 'YYYY-MM-DD'}}

# @name login
GET {{host}}
Content-Type: application/json

###

# @name health-check
GET {{module}}/health-check
Content-Type: application/json
Authorization: Bearer {{token}}