@token = {{login.response.body.message}}
@today={{$localDatetime 'YYYY-MM-DD'}}

# @name login
GET {{host}}
Content-Type: application/json

###

# @name healthCheck
GET {{host}}/{{token}}
Content-Type: application/json
Authorization: Bearer {{token}}